name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Specify the required Python version

    # Step 3: Upgrade pip and setuptools, then install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt

    # Step 4: Run the build script
    - name: Build Application
      run: ./build.sh
